# Generated by Django 4.0.1 on 2022-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UkTowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='town name', max_length=45)),
                ('county', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=16)),
                ('grid_reference', models.CharField(max_length=8)),
                ('easting', models.IntegerField()),
                ('northing', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('postcode_sector', models.CharField(max_length=44)),
                ('nuts_region', models.CharField(max_length=24)),
                ('type', models.CharField(max_length=16)),
            ],
        ),
    ]
