# Generated by Django 4.0.1 on 2022-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_countyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_name',
            field=models.ManyToManyField(to='towns.CountyName'),
        ),
    ]
