# Generated by Django 4.0.1 on 2022-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_alter_uktowns_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uktowns',
            name='country',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='uktowns',
            name='name',
            field=models.CharField(help_text='town name', max_length=45, unique=True),
        ),
    ]
