# Generated by Django 4.0.1 on 2022-01-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0004_alter_uktowns_country_alter_uktowns_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uktowns',
            name='name',
            field=models.CharField(help_text='town name', max_length=45),
        ),
    ]
